<a href="https://colab.research.google.com/github/iestleija/4808-Programacion/blob/Unidad1/Unidad1/Practices/Practica4_266229.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Maestría en Intelingencia Artificial y Analítica de Datos**

- Curso: Programación para Analítica Descriptiva y Predictiva

- Semestre: Enero-Junio

- Profesor: Dr. Vicente García Jiménez
- Práctica: 04 Manipulación de matrices
- Alumno: Ismael Estrada Leija
- Matrícula: 266229

# Práctica #4 - Unidad 1. Manipulación de matrices

## Instrucciones
Manipulación de matrices.

Crea dos matrices de 3x3 con números aleatorios entre 1 y 10. Realiza las siguientes operaciones:

1. Suma ambas matrices.
2. Resta la segunda matriz de la primera.
3. Multiplica la primera matriz por 2.
4. Realiza una multiplicación matricial entre las dos matrices.

No olvides enviar el archivo TXT con la liga a tu notebook en Google Colab y Github

## Crea dos matrices de 3x3 con números aleatorios entre 1 y 10

### Preparación del ambiente
Se importa numpy y se establece una semilla global para los calculos aleatorios.

In [22]:
import numpy as np

# Set the global seed
np.random.seed(12)

### Creación de las dos matrices
Se crean las matrices A y B, ambas con dimension 3x3 y valores aleatorios entre 1 y 10.

In [23]:
# create matrices
A = np.random.randint(1, 11, size=(3, 3))
B = np.random.randint(1, 11, size=(3, 3))
print(A)
print(B)

[[7 2 3]
 [4 4 1]
 [7 2 5]]
[[ 6 10  3]
 [ 7  1  6]
 [ 9  3 10]]


### 1. Suma Matricial
Debido a que las matrices fueron generadas por numpy, la adición de las mismas se realiza conforme al álgebra lineal, elemento a elemento. *Es importante anotar que las listas nativas de Python durante la suma se concatenan.*

In [24]:
# Matrices addition executed by Numpy
print(A+B)

[[13 12  6]
 [11  5  7]
 [16  5 15]]


### 2. Resta Matricial
De igual forma que la suma la sustracción matricial la ejecuta Numpy, acorde a la convención matemática.

In [25]:
# Sustraction of matrices made by Numpy
print(A-B)

[[ 1 -8  0]
 [-3  3 -5]
 [-2 -1 -5]]


### 3. Multiplicación de Matriz por un Escalar
Se presenta ahora la multiplicación de la matriz A por un escalar, la que conforme a la teoría matemática resulta de multiplicar el escalar por cada elemento y ese valor colocarlo en la misma posición del elemento en la nueva matriz.

In [26]:
# multiplication of a matrix by an scalar value
print(A*2)

[[14  4  6]
 [ 8  8  2]
 [14  4 10]]


### 4. Multiplicación algebráica de matrices
La multiplicación de matrices se efectúa con el método np.dot de Numpy, el cual sigue el principio de calcular cada nuevo elemento de la matriz resultante mediante el producto punto de la fila de la primera matriz y la columna de la segunda que intersectan en la posición de ese elemento precisamente.

In [27]:
# Algebraic matrices multiplication made with np.dot method
print(np.dot(A, B))

[[ 83  81  63]
 [ 61  47  46]
 [101  87  83]]
